version: '3.3'
services:
  evolution-api:
    image: atendai/evolution-api:v2.2.0
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTHENTICATION_API_KEY=B8988582-7067-463E-A4C3-A3F0E0D06939
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution_password@postgres:5432/evolution
      - DATABASE_CLIENT_NAME=evolution_exchange
      - CACHE_REDIS_ENABLED=false
      - CACHE_REDIS_URI=redis://redis:6379/1
      - CACHE_REDIS_PREFIX=evolution
      - CACHE_LOCAL_ENABLED=true
      - S3_ENABLED=false

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution_password
      POSTGRES_DB: evolution
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis_data:/data

volumes:
  evolution_postgres_data:
  evolution_redis_data:
